meta:
  author: Stephen Hutchings
  homepage: http://typicons.com/
  twitter: https://twitter.com/Typicons/
  license: CC BY-SA 3.0
  license_url: http://creativecommons.org/licenses/by-sa/3.0/

  css_prefix: "typcn"
  columns: 12

transform:
  baseline: 0.5
  rescale: 1.2

font:
  version: "2.0"

  # lowercase only
  fontname: typicons

  fullname: Typicons
  familyname: Typicons

  copyright: (c) Stephen Hutchings 2012

  ascent: 850
  descent: 150
  weight: Book

glyphs:
  - uid: c2c0dca2cbf54863aad7e8b645fc81ee
    css: adjust-contrast
    code: 0x2710
    search: [adjust contrast black white balance]
  - uid: cad24dc427004a65a45cc8e31385e77d
    css: anchor
    code: 0x2711
    search: []
  - uid: 2d655bf0f4194021a131a7ffd03d3352
    css: archive
    code: 0x2712
    search: [box storage save backup]
  - uid: 8ea5621f4cc64187a33096adad5dbc53
    css: arrow-back
    code: 0x2713
    search: [arrow back]
  - uid: ec8a6127d5234dbfaaf3fa6f57190e57
    css: arrow-down
    code: 0x2714
    search: [arrow down]
  - uid: d766b6bd63a645349f510eddeb721e8d
    css: arrow-forward
    code: 0x2715
    search: [arrow forward]
  - uid: 563f269c4fe1496593242f070d439139
    css: arrow-left
    code: 0x2716
    search: [arrow left]
  - uid: ad98787397d640358eec2efbdf13fb3c
    css: arrow-line-down
    code: 0x2717
    search: [arrow line down]
  - uid: 072a6e053c72495897820fa84cb93a3c
    css: arrow-line-left
    code: 0x2718
    search: [arrow line left]
  - uid: 21817868005843e3bfccec9a9caf258d
    css: arrow-line-right
    code: 0x2719
    search: [arrow line right]
  - uid: bd025684aade4db2a42ebde4c37bc102
    css: arrow-line-up
    code: 0x271a
    search: [arrow line up]
  - uid: ea11c8b4bb4c4807bdf63b6348c14cd6
    css: arrow-loop
    code: 0x271b
    search: [arrow loop return again repeat]
  - uid: 9f7c629d49624c24a8d7305ce59b3b1e
    css: arrow-maximise
    code: 0x271c
    search: [arrow maximise expand increase]
  - uid: f9b5af4ee455469c909ce116f006d6b4
    css: arrow-merge
    code: 0x271d
    search: [arrow merge combine unite]
  - uid: 3a9e752906964175b3860adc5bfa8d20
    css: arrow-minimise
    code: 0x271e
    search: [arrow minimise reduce decrease]
  - uid: b0d4a6be75d1493aa56e1338e037557d
    css: arrow-move
    code: 0x271f
    search: [arrow move four directions]
  - uid: c88126f3900a4c09b7f9e30b867b19ad
    css: arrow-repeat
    code: 0x2720
    search: [arrow repeat loop return again]
  - uid: 99127c73de7b496aa7338a3191eee29c
    css: arrow-right
    code: 0x2721
    search: [arrow right]
  - uid: dda55d8d0493473ebaa62a39299a1036
    css: arrow-shuffle
    code: 0x2722
    search: [arrow shuffle mix disorder]
  - uid: ed66f42a199d4490af61f1b6529957a8
    css: arrow-split
    code: 0x2723
    search: [arrow split]
  - uid: e130f482fe754ec5a4baa8f0a34e2f76
    css: arrow-sync
    code: 0x2724
    search: [arrow sync recycle reuse]
  - uid: 2bf1099608344996a7295227f68b2940
    css: arrow-up
    code: 0x2725
    search: [arrow up]
  - uid: eeb4f77ef0264ec9a9b3eab632df105f
    css: at
    code: 0x2726
    search: [sign symbol]
  - uid: 80e3f29dc698493f80914c631e627a62
    css: attachment
    code: 0x2727
    search: [attachment paper clip]
  - uid: c58d17932d794f3ebe776ec160db5a40
    css: backspace
    code: 0x2728
    search: [backspace delete]
  - uid: 2ee5270b8bb64fe79fe8127a302d75e1
    css: battery-charge
    code: 0x2729
    search: [battery charge charging plugged powered]
  - uid: 4746b000c4a646a4a32c37da49d178a3
    css: battery-full
    code: 0x272a
    search: [battery full power]
  - uid: 91e00849ea4b4bf0bb5c2ad60d4da6aa
    css: battery-high
    code: 0x272b
    search: [battery high power]
  - uid: 8201c3379ae047fd9c38c449e428477e
    css: battery-low
    code: 0x272c
    search: [battery low power]
  - uid: dbc5d9d1b7f841f2be75a27b472be082
    css: battery-mid
    code: 0x272d
    search: [battery middle medium power]
  - uid: 761608d879ff49ed8fb2c80ee6ce71aa
    css: beaker
    code: 0x272e
    search: [beaker beta labs experiment]
  - uid: d97a161538b0469e9ef9f0c5911aa40d
    css: beer
    code: 0x272f
    search: [beer drink ale alcohol]
  - uid: aef7aaee06164fa993bf6ecda631c315
    css: bell
    code: 0x2730
    search: [alarm ring alert sound]
  - uid: b716a9d6c19f4204b61f2c055cf64275
    css: book
    code: 0x2731
    search: [read album]
  - uid: ae2108466e70400b91d85a76f7fab017
    css: bookmark
    code: 0x2732
    search: [save keep for later]
  - uid: 62daf7a5baef41be9f93ea18f5d4c0a0
    css: briefcase
    code: 0x2733
    search: [luggage]
  - uid: 72c653abb80e4343af0bdbd435b70628
    css: brush
    code: 0x2734
    search: [paintbrush]
  - uid: 6d6a2e74c6414f98ba74e3db16ef7705
    css: business-card
    code: 0x2735
    search: [vcard details business card]
  - uid: 8ec355a1bd17451bbac513d9dac25142
    css: calculator
    code: 0x2736
    search: [maths]
  - uid: 75bd3c103536437a8bafa0e2f502dc04
    css: calender
    code: 0x2737
    search: [date]
  - uid: 81957220fdd94585ac9d492072ed5e1f
    css: camera
    code: 0x2738
    search: [photo photograph]
  - uid: 833f0bee73034187a1e5d7d62225d0f6
    css: chart-area
    code: 0x2739
    search: [chart area graph]
  - uid: 5832584229024bbaa7fb58de3161cee2
    css: chart-bar
    code: 0x273a
    search: [chart bar graph]
  - uid: 652f983ef442468e8d75274418230bea
    css: chart-line
    code: 0x273b
    search: [chart line graph]
  - uid: 79abf44d2bc7407cb82da2e44eb76195
    css: chart-pie
    code: 0x273c
    search: [chart pie graph]
  - uid: d0dc86be39bf4c7dbaa040e889353cc5
    css: chat-typing
    code: 0x273d
    search: [chat message typing]
  - uid: d067143edab14ca8b908ea9f9ac8dca6
    css: chevron-left
    code: 0x273e
    search: [chevron left less than]
  - uid: 7238ab9b2b104e118cabd5287ebd00cf
    css: chevron-right
    code: 0x273f
    search: [chevron right more than]
  - uid: 4c6c397bd5e84bac8a2b1dbd80c4fa10
    css: clipboard
    code: 0x2740
    search: []
  - uid: 0b24b308aa28455ba202e36b96169f0b
    css: cloud-storage
    code: 0x2741
    search: [cloud storage upload]
  - uid: 06d55600d03c4e46ad640ebc8ce7e982
    css: code
    code: 0x2742
    search: [script]
  - uid: bd11f9d8817245799117ba0a2287edae
    css: coffee
    code: 0x2743
    search: [beverage drink caffeine tea]
  - uid: c41816dc03944f7e89159ffbb5a7ab90
    css: cog
    code: 0x2744
    search: [settings properties edit]
  - uid: 239c6249d9404d90b0103fbfd8f1375d
    css: compass
    code: 0x2745
    search: [directions safari]
  - uid: 4dd58d174cb143a0bd79db081d4d4a1b
    css: contacts
    code: 0x2746
    search: [album friends]
  - uid: 68463a688d6a4bf388dd0ccabf0821f6
    css: credit-card
    code: 0x2747
    search: [purchase pay money]
  - uid: 4a38aec328394774b87333fcaf7afadf
    css: database
    code: 0x2748
    search: [storage server]
  - uid: be51654928274a9883cd94f418f44a84
    css: delete
    code: 0x2749
    search: [cancel]
  - uid: 3a7cbcd9c57c40f8a82ea1f904c9b869
    css: device-desktop
    code: 0x274a
    search: [device desktop computer]
  - uid: 40307788aff0494cb09ad1e4136099a4
    css: device-laptop
    code: 0x274b
    search: [device latop computer netbook]
  - uid: 79da8747f37e4022b90d3343e49e7cca
    css: device-phone
    code: 0x274c
    search: [device phone mobile smartphone]
  - uid: a920666f9461427c82e5e518c56952a8
    css: device-tablet
    code: 0x274d
    search: [device tablet]
  - uid: 2385255ea9da4df392699080a4c4f93a
    css: directions
    code: 0x274e
    search: [signpost guide help]
  - uid: 0ac1aa6f5be240eea5ea9bd29a9a292f
    css: divide
    code: 0x274f
    search: [division maths]
  - uid: 766d96be9b7348f9a26e977d96b5a2b4
    css: document-add
    code: 0x2750
    search: [document add]
  - uid: 2542f7dfd1fa411ebe0f7d95fe4d3630
    css: document-delete
    code: 0x2751
    search: [document delete]
  - uid: 7c449fbd473d44a1808b3c6925ce319a
    css: document-text
    code: 0x2752
    search: [document text words]
  - uid: b5f7c6010d3447e39aee90777e871e55
    css: document
    code: 0x2753
    search: []
  - uid: ce34443a806f49cd9b9a67e0461ee2a1
    css: download
    code: 0x2754
    search: []
  - uid: 0de03f3bab5e4f8d916c57f120ef26bf
    css: edit
    code: 0x2755
    search: [pencil change]
  - uid: 5e223bfc72a14c5295a63ff0d850c750
    css: eject
    code: 0x2756
    search: [remove]
  - uid: 765918ba5773482082e4d3ea3149fc8e
    css: equals
    code: 0x2757
    search: []
  - uid: 6c61af2ad0e944e4abcbdd33cc03f49d
    css: export
    code: 0x2758
    search: []
  - uid: 569a1a05bc6144aabb39b34e574247f7
    css: eye
    code: 0x2759
    search: [view look gallery]
  - uid: 240e43d9f0784df4a6e3c2c47bfd6454
    css: feather
    code: 0x275a
    search: [soft nature]
  - uid: a4164172c4e7498b9777c8fd38891b54
    css: film
    code: 0x275b
    search: [filmstrip]
  - uid: 73ec99a0941c474f99905aaf1fca365d
    css: flag
    code: 0x275c
    search: []
  - uid: a045fa358b494f8384f211fde83042fe
    css: flash
    code: 0x275d
    search: [lightning strike]
  - uid: 804a7ee524984372b58435472f8890d5
    css: folder-add
    code: 0x275e
    search: [folder add]
  - uid: 2dff850acd6e4d6abf0740ad32acbe36
    css: folder-delete
    code: 0x275f
    search: [folder delete]
  - uid: d6a3eb0f386740d289b125b516fe00ac
    css: folder
    code: 0x2760
    search: []
  - uid: b888089a77f546bda4763722aecfdccc
    css: gift
    code: 0x2761
    search: [present]
  - uid: cf1b26bab78f4dd0b7f17c4594aa6132
    css: globe
    code: 0x2762
    search: [world]
  - uid: 1b8ec770ce3f40098b6c70208dbb60e1
    css: group
    code: 0x2763
    search: [collection users]
  - uid: 8ca968c0154449d78f9d48aea35ccf8e
    css: headphones
    code: 0x2764
    search: []
  - uid: a27c0197e1c249b9af6d132adb11c50f
    css: heart
    code: 0x2765
    search: []
  - uid: 5c7627271638483bb4dab2f9d3ab063d
    css: home
    code: 0x2766
    search: []
  - uid: 2379acbb8eec4b45a987409b554487d0
    css: image
    code: 0x2767
    search: []
  - uid: 88a1e0841f734dbda996fa401a20b20c
    css: infinity
    code: 0x2768
    search: []
  - uid: a8bf621b9ca94d799fce58d528309514
    css: info-large
    code: 0x2769
    search: []
  - uid: 131dbf64d4a84b78acd48b1a1b7c22f1
    css: info
    code: 0x276a
    search: []
  - uid: af950a8ce9864b6d8c1134a727152656
    css: input-checked
    code: 0x276b
    search: []
  - uid: a2bdd89b3d1442f78f6f13b9e56a9d1e
    css: key
    code: 0x276c
    search: []
  - uid: 3ca30ff0b2904f508ff79939eb30d08f
    css: leaf
    code: 0x276d
    search: []
  - uid: 88acbaf7046d4c34a53845a39ccdbf8a
    css: lightbulb
    code: 0x276e
    search: []
  - uid: 729247152802412f99ec09dff20a9080
    css: link
    code: 0x276f
    search: []
  - uid: 01a57d428814453f974ef85068c4fd61
    css: location-services
    code: 0x2770
    search: []
  - uid: 27f33249ddc0416c837c7d87f78aa1de
    css: lock-closed
    code: 0x2771
    search: []
  - uid: ca6dce45090041b9ab311ae52035376b
    css: lock-open
    code: 0x2772
    search: []
  - uid: 8dec08996ddf4316968d0d0425edeab7
    css: mail
    code: 0x2773
    search: []
  - uid: 10c3395b49ee40dca48793f0558d375d
    css: map-location
    code: 0x2774
    search: []
  - uid: 9770e3c842a74d27b13296ecbb7faed2
    css: map
    code: 0x2775
    search: []
  - uid: 02ca9d57b8694317a120a93732189304
    css: media-eject
    code: 0x2776
    search: []
  - uid: aa35a1be32d24dd3bfcd0df2b6d56604
    css: media-fast-forward
    code: 0x2777
    search: []
  - uid: 0de65fd4a07140078bd547184b1b10cb
    css: media-play
    code: 0x2778
    search: []
  - uid: 2efdfe797a494c80ad825c101958ec07
    css: media-record
    code: 0x2779
    search: []
  - uid: c8afb77e538f46b7a7479cbc5e3bb158
    css: media-rewind
    code: 0x277a
    search: []
  - uid: 9a0c29d7fb084bda8c3ff7a3f9e0ac11
    css: media-stop
    code: 0x277b
    search: []
  - uid: 82d71cfa84f245ae93d284f9da1484d3
    css: menu
    code: 0x277c
    search: []
  - uid: 0dd00befb4e84c2d81be874b35ef1b21
    css: message
    code: 0x277d
    search: []
  - uid: 6e93328ca132439f9b4ea92620753669
    css: messages
    code: 0x277e
    search: []
  - uid: 2d8d54ff463b432a8b3407b5a3796812
    css: microphone
    code: 0x277f
    search: []
  - uid: a778ec7a3f084bb59c5fa2f895304b5b
    css: minus
    code: 0x2780
    search: []
  - uid: 2cdd44729aad4e328140c0707e84bb06
    css: news
    code: 0x2781
    search: []
  - uid: 346292550ccb4102ab6360e1db642847
    css: notes
    code: 0x2782
    search: []
  - uid: e01e2566135641758dada514633ca6f3
    css: pen
    code: 0x2783
    search: []
  - uid: 40372134a99f4905a6e1f0f5261aa330
    css: pencil
    code: 0x2784
    search: []
  - uid: ff11d8da9b19466bbb7c2dd765f976f7
    css: phone
    code: 0x2785
    search: []
  - uid: dc1fc720b0fd4f0294f2c76d56312969
    css: pi
    code: 0x2786
    search: []
  - uid: 23c1e62af215485295b37e3910c7d9f3
    css: pin
    code: 0x2787
    search: []
  - uid: 698b1512170f4b28b8e78257797e3287
    css: pipette
    code: 0x2788
    search: []
  - uid: ff750058ce3445c68a97be923b81efae
    css: plane
    code: 0x2789
    search: []
  - uid: 77d5072cb15f46e98f54d9211261e5bd
    css: plug
    code: 0x278a
    search: []
  - uid: cf45729fe44f40938afe41612a2a8533
    css: plus
    code: 0x278b
    search: []
  - uid: 16ba83d4e9b541afba0b4779bde256cb
    css: point-of-interest
    code: 0x278c
    search: []
  - uid: 02a10071ae4943959009ae11feea0d0f
    css: power
    code: 0x278d
    search: []
  - uid: 2acac8f145e94a64a69a00461d87fe9e
    css: printer
    code: 0x278e
    search: []
  - uid: d17e71278d3e4a78b9383dbce792c640
    css: puzzle
    code: 0x278f
    search: []
  - uid: f6eb1f9ffffa4c27b5ea37185206afc7
    css: radar
    code: 0x2790
    search: []
  - uid: 4797fcad549c4d698aa353b125eb3620
    css: refresh
    code: 0x2791
    search: []
  - uid: 1009fdc04ad441fa8961897b3d5ba980
    css: rss
    code: 0x2792
    search: []
  - uid: a5d7ce9a14cf420590c9de6f49a48261
    css: scissors
    code: 0x2793
    search: []
  - uid: 77efca8845c045668f50429fcd15b5c2
    css: shopping-cart
    code: 0x2794
    search: []
  - uid: 68a40e2cf84445158d353d7be080605b
    css: shopping-bag
    code: 0x2795
    search: []
  - uid: c88eecee7b9b46f783358c4fc012daa6
    css: social-dribbble
    code: 0x2796
    search: []
  - uid: 049e26dcb67746cabf81df1fffc98bf5
    css: social-facebook
    code: 0x2797
    search: []
  - uid: 77091a8f422947e4969931f8c840107d
    css: social-flickr
    code: 0x2798
    search: []
  - uid: 57f883093cf64d38806de0450bf46ddf
    css: social-linkedin
    code: 0x2799
    search: []
  - uid: 6baa59436201467fb88d921f05373001
    css: social-pinterest
    code: 0x279a
    search: []
  - uid: a3a0d5e3fb5145e8a7339d2d55ca9fd6
    css: social-skype
    code: 0x279b
    search: []
  - uid: ad74f480b3c44fdfade1d4be05999c32
    css: social-tumbler
    code: 0x279c
    search: []
  - uid: c4d4db94a5f34e4392651a3dd87da7ff
    css: social-twitter
    code: 0x279d
    search: []
  - uid: f52d6a1156064ec7a000324f44a26589
    css: social-vimeo
    code: 0x279e
    search: []
  - uid: 7fed96525e314587a8eb6b6d1a3a7dce
    css: sort-alphabetically
    code: 0x279f
    search: []
  - uid: 6702ac9569c64707b6ada623ba02992b
    css: sort-numerically
    code: 0x27a0
    search: []
  - uid: 934891c650e544aaa0a098309e0f7ce9
    css: spanner
    code: 0x27a1
    search: []
  - uid: 724f07b89e5a4916b3e3ea50f8553c7b
    css: star
    code: 0x27a2
    search: []
  - uid: b4b5977312ab48ff9a134e9f7b4b2f1e
    css: stopwatch
    code: 0x27a3
    search: []
  - uid: 867fc20e715e4b4c992c0b38e637c0aa
    css: support
    code: 0x27a4
    search: []
  - uid: 30016c5419de41a99bc4cb59c51036fe
    css: tabs
    code: 0x27a5
    search: []
  - uid: 976a9aa59adf474a8a0ee833ddc433a6
    css: tag
    code: 0x27a6
    search: []
  - uid: 8e8bccc74d114b7288438671eda98299
    css: tags
    code: 0x27a7
    search: []
  - uid: ef7c3629735f4a1f85374622462f0455
    css: th-large
    code: 0x27a8
    search: []
  - uid: 28374dea176e42cfb0e509d0ff6350f8
    css: th-list
    code: 0x27a9
    search: []
  - uid: 9430acc1667a432b80cdf1f9dfbd8e13
    css: th-small
    code: 0x27aa
    search: []
  - uid: c4ce8c82074c43d39ed56f59be14d864
    css: thermometer
    code: 0x27ab
    search: []
  - uid: dbb88a8c2f2d469fa49f2661ddf5e9a7
    css: thumbs-down
    code: 0x27ac
    search: []
  - uid: aea6a89697b84b4abc75ee41f2c751f7
    css: thumbs-up
    code: 0x27ad
    search: []
  - uid: 12938a780bd640d19f9622b390bdf8d7
    css: tick
    code: 0x27ae
    search: []
  - uid: b1641b0699464abfa10e387cfd62c186
    css: ticket
    code: 0x27af
    search: []
  - uid: 834ee94b1a8e48e6a0aa28d5594d5be5
    css: time
    code: 0x27b0
    search: []
  - uid: 928298ce69d6466bbe3dafb4ac5e6af3
    css: times
    code: 0x27b1
    search: []
  - uid: 3a13096407064ec28f2c4ddc38781a21
    css: trash
    code: 0x27b2
    search: []
  - uid: 74215b6da5ef4c09b49d9f69837e30ae
    css: tree
    code: 0x27b3
    search: []
  - uid: b1193155fcc245d0a651195a699da5d3
    css: upload
    code: 0x27b4
    search: []
  - uid: 7e2815c455a74c1d8e8833fdd2f4a831
    css: user-add
    code: 0x27b5
    search: []
  - uid: b36365a642834029a5000cd85cbbaf5e
    css: user-delete
    code: 0x27b6
    search: []
  - uid: a8b77009a1644849a6096d0ca5418cd1
    css: user
    code: 0x27b7
    search: []
  - uid: fa2e45679ed447448c91798d37d47009
    css: video
    code: 0x27b8
    search: []
  - uid: 7301d2d3051849959eb4f50a7e535dcd
    css: volume-mute
    code: 0x27b9
    search: []
  - uid: e6f0280045fb4f43aa951a9eb51e55b4
    css: volume-up
    code: 0x27ba
    search: []
  - uid: 3ef9f75f5e094d23b8b56a14d110cafb
    css: volume
    code: 0x27bb
    search: []
  - uid: de723df923894cd69a9b12ced0502d41
    css: voume-down
    code: 0x27bc
    search: []
  - uid: fb461b00f893458a8dd3be478821556a
    css: warning
    code: 0x27bd
    search: []
  - uid: 85fa298639504ff9887c56fca42e0963
    css: watch
    code: 0x27be
    search: []
  - uid: 10246edc330d4f108376713f1ad0828b
    css: waves
    code: 0x27bf
    search: []
  - uid: bd61193a86884a0e905fa0d7df039d56
    css: weather-cloudy
    code: 0x27c0
    search: []
  - uid: 16b3dc50cd2c4d49b8c524da98b50b8a
    css: weather-downpour
    code: 0x27c1
    search: []
  - uid: bbe83d3cc12f4e4f91564d8a2499bc82
    css: weather-night
    code: 0x27c2
    search: []
  - uid: 27f0771e0281493e80f89952aa2a8d0e
    css: weather-partly-sunny
    code: 0x27c3
    search: []
  - uid: 95ad03132f37436c8ca0be52b446c0fc
    css: weather-shower
    code: 0x27c4
    search: []
  - uid: cf80cdab4fc34d7bbe8435829bd0b94c
    css: weather-snow
    code: 0x27c5
    search: []
  - uid: b538d0367f8a4ef9b8c63cac43850747
    css: weather-stormy
    code: 0x27c6
    search: []
  - uid: a822f3640b2c4698b19396d1351e431c
    css: weather-sunny
    code: 0x27c7
    search: []
  - uid: 8e1d069001f8449fac30a82c253d713a
    css: weather-windy-cloudy
    code: 0x27c8
    search: []
  - uid: 1e76357df0404c089372c40660e26ba8
    css: weather-windy
    code: 0x27c9
    search: []
  - uid: 44d49c0b7e524336b303595547e0270e
    css: wi-fi
    code: 0x27ca
    search: []
  - uid: fe3d0a9a6a0946eba681cf4de4c4da11
    css: wine
    code: 0x27cb
    search: []
  - uid: 132c45f8efdd4369b62cf68a24bc35c4
    css: world
    code: 0x27cc
    search: []
  - uid: 2888ecb993e14a91a845c41847ae3056
    css: zoom-in
    code: 0x27cd
    search: []
  - uid: 50d22d95a8eb4e969545e8ba76c84928
    css: zoom-out
    code: 0x27ce
    search: []
  - uid: 277bae765c2247d885b4566b3e46e0dc
    css: zoom
    code: 0x27cf
    search: []